// 전역 설정 (SseProvider를 적용한 루트 레이아웃.)
import React from 'react';
import { SseProvider } from '@/context/SseContext';

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body>
        <SseProvider>
            {children}
        </SseProvider>
        </body>
        </html>
    );
}


// import React from 'react';
// import "./globals.css";
//
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

